logging:
  level:
    sample: DEBUG

grpc:
  port: 6565
  client:
    host: localhost
    port: 6565

#Uncomment the follow three lines to disable reporting to zipkin.
sample:
  zipkin:
    enabled: false

spring:
  application:
    name: testSleuthGrpc
  sleuth:
    sampler:
      probability: 1.0
    